### ISSUE TITLE
max_intersect_distance is not always used as constraint

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/building-boundary#1]
There are still situations where there are long spikes in the boundary output. 
One approach might be to use a maximum_angle for a vertex? In that case vertices that have a very narrow angle from the edges can simply be discarded.

**Comment by chrislcs** [comment]
This constraint was removed in 99e08bb6f0ca746062baaa4e5d701d0d8f35f11e , and is thus no longer relevant. It now always checks both the intersection between the two segments and the intersections if a perpendicular line is added between and uses the perpendicular line if that intersection is closer than the intersection of the two segments.
