### ISSUE TITLE
Merge lines that are parallel but have a small offset

### ISSUE THREAD

**Issue by tomvantilburg** [Geodan/building-boundary#7]

**Comment by skyimager** [comment]
Hi, does the library work with Python 3.x? I have been trying to install cgal-bindings for 2 days now, but there seems to be some dependency of PCL with Python 2.7

**Comment by chrislcs** [comment]
Please use an appropriate issue to post a question (either reply to an existing issue that is similar to your question if that exists or create a new issue). 

Regarding your question: I am using python 3. As I said before I am not able to provide support (yet). Everything is still very experimental. For support on dependencies you can try asking the maintainers of those packages. I could just use `pip install cgal-bindings` to install these bindings.
